# Generated by Django 5.2.1 on 2025-05-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignatura',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='asignatura',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='archivo',
            name='trimestre',
            field=models.IntegerField(choices=[(1, '1º Trimestre'), (2, '2º Trimestre'), (3, '3º Trimestre'), (4, 'Vacaciones')]),
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
