# Generated by Django 5.2.1 on 2025-05-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_remove_asignatura_curso_remove_asignatura_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='nombre',
            field=models.CharField(default='Sin nombre', max_length=100),
        ),
    ]
