# Generated by Django 5.2.1 on 2025-05-19 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_usuario_fecha_creacion_padre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('alumno', 'Alumno'), ('padre', 'Padre'), ('admin', 'Administrador')], max_length=10),
        ),
    ]
