# Generated by Django 5.2.1 on 2025-05-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_asignatura_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='enlace_externo',
            field=models.URLField(blank=True, null=True, verbose_name='Enlace externo (opcional)'),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='archivos/'),
        ),
    ]
