# Generated by Django 5.2.1 on 2025-05-22 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_usuario_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudEliminacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('procesado', models.BooleanField(default=False)),
                ('archivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.archivo')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
