# Generated by Django 5.2.1 on 2025-05-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_archivo_enlace_externo_alter_archivo_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='enlace_externo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
