# Generated by Django 5.2.1 on 2025-05-12 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_alter_archivo_enlace_externo'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='curso',
            field=models.CharField(choices=[('1P', '1º Primaria'), ('2P', '2º Primaria'), ('3P', '3º Primaria'), ('4P', '4º Primaria'), ('5P', '5º Primaria'), ('6P', '6º Primaria'), ('1S', '1º Secundaria'), ('2S', '2º Secundaria'), ('3S', '3º Secundaria'), ('4S', '4º Secundaria')], default='1P', max_length=2),
            preserve_default=False,
        ),
    ]
