# Generated by Django 5.2.1 on 2025-05-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_archivo_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('curso', models.CharField(choices=[('1P', '1º Primaria'), ('2P', '2º Primaria'), ('3P', '3º Primaria'), ('4P', '4º Primaria'), ('5P', '5º Primaria'), ('6P', '6º Primaria'), ('1S', '1º Secundaria'), ('2S', '2º Secundaria'), ('3S', '3º Secundaria'), ('4S', '4º Secundaria')], max_length=2)),
            ],
        ),
    ]
