# Generated by Django 5.2.1 on 2025-05-18 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_alumno_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('admin', 'Administrador General'), ('padre', 'Padre'), ('alumno', 'Alumno')], default='padre', max_length=10),
        ),
    ]
